### ISSUE TITLE
It not work on latest pi os

### ISSUE THREAD

**Issue by chengjianwen** [chesty/overlayroot#12]
I tried again and again with the latest pi os 2020-08-20 with kernel 5.4.51-v7l+.

**Comment by chesty** [comment]
in what way doesn't it work?

**Comment by chengjianwen** [comment]
No init found. Try passing init= bootarg.

then show a busybox prompt with a (initramfs).
df show that there is no overlay mount point was mounted, but tmpfs named /overlay exists.

**Comment by chesty** [comment]
cheers. I'll download the latest and see what's going on.

**Comment by chengjianwen** [comment]
Sorry, my enviroment is a little fuzzy, and I tried on a fresh pi os, it worked. So it maybe somewhere error else.
