### ISSUE TITLE
Create a tag so there is a known stable point

### ISSUE THREAD

**Issue by foxy82** [chesty/overlayroot#15]
Hey - thanks for this I'm currently testing it out on a Raspberry Pi Zero W running DietPi.

I know this repo has been stable for a long time now but I was wondering if we could create a tag / "release". So that if I install this on multiple Pis I don't have to just clone master which always risks moving on. It would be much better to be able to clone a tag or a release to ensure all versions are the same.

Thanks.

**Comment by chesty** [comment]
A lot of people fork it on github, leave it unmodified and use their fork. But, adding a tag sounds like a good idea so I'll do that. 

thanks.

**Comment by chesty** [comment]
No idea if I did it right but there's a release.

thanks for the suggestion, let me know if it's not right. cheers.

**Comment by foxy82** [comment]
Thanks the tag works for me as now we can just wget "https://github.com/chesty/overlayroot/archive/refs/heads/v1.0.0.zip"
