### ISSUE TITLE
Complete install script for raspberry pi?

### ISSUE THREAD

**Issue by philippejadin** [chesty/overlayroot#2]
First thank you for your work, this seems like a robust solution for read only overlayed root fs for raspberry. I was wondering if you'd be interested to provide an install script that would do all the work? If yes, I think I can make a pull request. My skills in bash are limited so you will need to look at it...
Sounds like a good idea?

**Comment by chesty** [comment]
go for it, I'll check it out and I might make some suggestions but I'll add.

**Comment by tampiss** [comment]
Great :-)
I can not wait. Im a noob, yet having continuous troubles with my RPI after power loose... I believe this may help me out, yet I have not clue how to implement.

Best, Martin

**Comment by ServeurpersoCom** [comment]
This repo is what I need for my robots thanks a lot Michael Chesterton !!!

**Comment by philippejadin** [comment]
I made a pull request for the install.sh script. It just mimics the readme :-)

**Comment by ServeurpersoCom** [comment]
Yes it's A MUST HAVE, it must be integrated on the rpi-setup - it's mandatory for IoT or Robotics.

**Comment by ServeurpersoCom** [comment]
An uninstall script is a good idea also, because we can't start/restart service inside chroot !
Edit: The install script must be idempotent and a "Disable+Reboot" / "Enable+Reboot" script pair is a better idea than a rootwork chroot script.

**Comment by chesty** [comment]
you can boot with `skipoverlay` in the kernel command line, see https://www.raspberrypi.org/documentation/configuration/cmdline-txt.md and it won't mount the overlay filesystem.

If I need to edit the root partition, maybe to update packages or edit a config file, I do the work in rootwork, exit, then reboot.

**Comment by ServeurpersoCom** [comment]
To disable overlay it's easy as a "#" inside the config.txt + reboot :

#initramfs init.gz

Now this is what I use to add/remove/update package inside my RO filesystem.
